#!/bin/sh

set -e

MCOLLECTIVE_CLIENT_CFG="/etc/mcollective/client.cfg"

case "$1" in
	configure)
		if [ ! -e "$MCOLLECTIVE_CLIENT_CFG" ]; then
			cp /usr/share/mcollective-client/client.cfg $MCOLLECTIVE_CLIENT_CFG
		fi

		chmod 600 $MCOLLECTIVE_CLIENT_CFG
	;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
