#!/bin/sh

set -e

MCOLLECTIVE_SERVER_CFG="/etc/mcollective/server.cfg"

case "$1" in
	purge)
		if [ -e "$MCOLLECTIVE_SERVER_CFG" ]; then
			rm -rf $MCOLLECTIVE_SERVER_CFG
			rmdir --ignore-fail-on-non-empty /etc/mcollective
		fi

	;;
	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|remove)
	;;
	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
	;;
esac

#DEBHELPER#

exit 0
